### ISSUE TITLE
Unnecessary code?

### ISSUE THREAD

**Issue by paul35621** [mrpeardotnet/WinProdKeyFinder#7]
It seems that you can remove `| (isWin8 & 2) * 4)` in KeyDecoder.cs. Since `isWin8 = ... & 1` it's always true that `isWin8 & 2 == 0`. Right?

**Comment by hobbygramerpro** [comment]
Exactly! `isWin8` is either `0` or `1`, hence `isWin8 & 2` is always `0`. But in that case, what is the variable even doing there?

**Comment by mrpeardotnet** [comment]
It is just about the part of a code, not functionality. No need to fix.
